name: Binder Keep Alive

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12h (UTC)
  workflow_dispatch:        # Permite execuÃ§Ã£o manual

jobs:
  ping-binder:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Binder session
        run: |
          curl -s "https://mybinder.org/v2/gh/Gabrie50/jupyter-desktop-server.git/HEAD" > /dev/null
          
